[pytest]
# TR: UI klasörü içinde testlerin aranacağı klasör.
# EN: Directory to search for tests within the UI folder.
testpaths = tests

python_files = test_*.py
python_functions = test_*
addopts = -v

# TR: Üst dizini (root) yola ekler.
# EN: Adds the parent directory (root) to the path.
pythonpath = ..

markers =
    regression: marks regression tests
    smoke: marks smoke tests